{{- if and .Values.imagePullSecret .Values.imagePullSecret.username .Values.imagePullSecret.password }}
{{- $registryAuthDocument := dict -}}
{{- $_ := set $registryAuthDocument "username" .Values.imagePullSecret.username }}
{{- $_ := set $registryAuthDocument "password" .Values.imagePullSecret.password }}
{{- $authMessage := printf "%s:%s" $registryAuthDocument.username $registryAuthDocument.password | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $dockerAuthDocument := dict .Values.imagePullSecret.registryURL $registryAuthDocument }}
{{- $dockerConfigJSONDocument := dict "auths" $dockerAuthDocument -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.secretName }}
  {{- if .Values.imagePullSecret.annotations }}
  annotations: {{- toYaml .Values.imagePullSecret.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.imagePullSecret.labels }}
  labels: {{- toYaml .Values.imagePullSecret.labels | nindent 4 }}
  {{- end }}
data:
  .dockerconfigjson: {{ $dockerConfigJSONDocument | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}